backend: 
  name: git-gateway
  branch: main

media_folder: static/assets
public_folder: /assets

collections: 
- name: "blog"
  label: "Blog"
  folder: "/blog"
  create: true
  slug: {{title}}
  media_folder: ''
  public_folder: ''
  editor: 
    preview: false
  
  fields: 
      - {name: title, label: Title, widget: string}
      - {name: description, label: Description, widger: string}
      - {name: tags, label: Tags, widget: list}
      - {name: date, label: 'Publish Date', widget: datetime}
      - {name: body, label: Body, widget: markdown}